name: 天气1

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: 目录
      run: |
          ls
    - name: 安装
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        pip3 install -r requirements.txt
    - name: 运行
      run: |
        python main.py
    
